<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <#if hasParent>

    <parent>
        <groupId>${groupId}</groupId>
        <artifactId>${parentArtifactId}</artifactId>
        <version>${version}</version>
    </parent>
    <artifactId>${artifactId}</artifactId>

    <#else>

    <groupId>${groupId}</groupId>
    <artifactId>${artifactId}</artifactId>
    <version>${version}</version>

    </#if>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <vertx.version>${vertx_version}</vertx.version>
        <domino.history.version>${domino_history_version}</domino.history.version>
        <domino.rest.version>${domino_rest_version}</domino.rest.version>
        <domino.ui.version>${domino_ui_version}</domino.ui.version>
        <domino.jackson.version>${domino_jackson_version}</domino.jackson.version>
        <domino.mvp.version>${domino_mvp_version}</domino.mvp.version>
        <gwt.version>${gwt_version}</gwt.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.dominokit</groupId>
                <artifactId>domino-mvp</artifactId>
                <version>${r"${domino.mvp.version}"}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.google.gwt</groupId>
                <artifactId>gwt</artifactId>
                <version>${r"${gwt.version}"}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.dominokit</groupId>
                <artifactId>domino-ui</artifactId>
                <version>${r"${domino.ui.version}"}</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-simple</artifactId>
                <version>1.7.30</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.assertj</groupId>
                <artifactId>assertj-core</artifactId>
                <version>3.20.2</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.dominokit</groupId>
                <artifactId>domino-jackson</artifactId>
                <version>${r"${domino.jackson.version}"}</version>
            </dependency>
            <dependency>
                <groupId>org.dominokit</groupId>
                <artifactId>domino-jackson</artifactId>
                <version>${r"${domino.jackson.version}"}</version>
                <classifier>sources</classifier>
            </dependency>
            <dependency>
                <groupId>org.dominokit</groupId>
                <artifactId>domino-jackson-processor</artifactId>
                <version>${r"${domino.jackson.version}"}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.dominokit</groupId>
                <artifactId>domino-rest-client</artifactId>
                <version>${r"${domino.rest.version}"}</version>
            </dependency>
            <dependency>
                <groupId>org.dominokit</groupId>
                <artifactId>domino-rest-processor</artifactId>
                <version>${r"${domino.rest.version}"}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.dominokit</groupId>
                <artifactId>domino-history-shared</artifactId>
                <version>${r"${domino.history.version}"}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>javax.validation</groupId>
            <artifactId>validation-api</artifactId>
            <version>1.0.0.GA</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.auto.service</groupId>
            <artifactId>auto-service</artifactId>
            <version>1.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.7.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.tomcat.maven</groupId>
                    <artifactId>tomcat7-maven-plugin</artifactId>
                    <version>2.2</version>
                </plugin>
                <plugin>
                    <groupId>net.ltgt.gwt.maven</groupId>
                    <artifactId>gwt-maven-plugin</artifactId>
                    <version>1.0.0</version>
                    <extensions>true</extensions>
                    <configuration>
                        <sourceLevel>${r"${maven.compiler.source}"}</sourceLevel>
                        <failOnError>true</failOnError>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>3.0.1</version>
                    <executions>
                        <execution>
                            <id>attach-sources</id>
                            <goals>
                                <goal>jar-no-fork</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <plugin>
                <groupId>net.ltgt.gwt.maven</groupId>
                <artifactId>gwt-maven-plugin</artifactId>
                <inherited>false</inherited>
                <configuration>
                    <launcherDir>${r"${project.build.directory}"}/gwt/launcherDir</launcherDir>
                </configuration>
            </plugin>
        </plugins>

    </build>

    <modules>
        <module>${artifactId}-frontend</module>
        <module>${artifactId}-backend</module>
        <#if generateApi>
        <module>${artifactId}-api</module>
        </#if>
    </modules>
</project>
