package org.dominokit.cli.generator;

import java.util.Map;
import java.util.function.Supplier;

/**
 * Contract for files generated by the scaffolding engine.
 */
public interface ProjectFile {

    /**
     * Returns the output file name.
     *
     * @return output file name
     */
    String getName();

    /**
     * Writes the file into the given path.
     *
     * @param path root path
     * @param context template context
     */
    void write(String path, Map<String, Object> context);

    /**
     * Returns the condition that decides whether this file is written.
     *
     * @return condition supplier
     */
    default Supplier<Boolean> condition() { return () -> true;}

}
