    <dependency>
        <groupId>${groupId}</groupId>
        <artifactId>${artifactId}-ui</artifactId>
        <version>${r"${project.version}"}</version>
    </dependency>
    <dependency>
        <groupId>${groupId}</groupId>
        <artifactId>${artifactId}-ui</artifactId>
        <version>${r"${project.version}"}</version>
        <classifier>sources</classifier>
    </dependency>
