#
# Copyright © ${year} Dominokit
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Deploy

on:
  push:
    branches: [ master, development ]

jobs:
  verify:
    strategy:
      matrix:
        java-version: [ 17 ]
    runs-on: ubuntu-20.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
      - run: ./mvnw verify -B -e

  release-ubuntu:
    needs: verify
    runs-on: ubuntu-20.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - uses: luangong/setup-install4j@v1
        with:
          version: 10.0.6
          license: ${{ secrets.INSTALL4J_LICENSE }}
      - name: development media
        if: false == contains(github.ref, 'master')
        run: ./mvnw -Pinstall4j package -e -B
      - name: release media
        if: contains(github.ref, 'master')
        run: ./mvnw -Pinstall4j,release package -e -B
      - run: mkdir staging && cp -r target/media/*.* staging
      - uses: actions/upload-artifact@v3
        with:
           name: Package
           path: staging